# 🔢 Módulo 6 — NumPy: Fundamentos

NumPy es la librería base para cálculo numérico en Python.
Ofrece:
- Arrays de alta eficiencia
- Operaciones vectorizadas
- Broadcasting
- Manipulación avanzada de datos numéricos

Este notebook cubre los fundamentos que necesitarás para análisis de datos, machine learning, ETL, simulaciones, etc.

---
## 1️⃣ Crear arrays de NumPy

Arrays básicos:

In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
a, b

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

Creación rápida de estructuras:

In [2]:
np.zeros((2,3)), np.ones((2,2)), np.arange(0,10,2), np.linspace(0,1,5)

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1.],
        [1., 1.]]),
 array([0, 2, 4, 6, 8]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

---
## 2️⃣ Propiedades de un array

- `ndim`: número de dimensiones
- `shape`: forma (filas, columnas)
- `size`: número total de elementos
- `dtype`: tipo de dato


In [3]:
x = np.array([[10,20,30],[40,50,60]])
x.ndim, x.shape, x.size, x.dtype

(2, (2, 3), 6, dtype('int64'))

---
## 3️⃣ Operaciones vectorizadas

Evitan bucles explícitos y son extremadamente rápidas.

In [4]:
v = np.array([1,2,3])
v*10, v+5, v**2

(array([10, 20, 30]), array([6, 7, 8]), array([1, 4, 9]))

Comparación con bucles de Python:

In [5]:
%timeit [x*2 for x in range(1000000)]
%timeit np.arange(1000000)*2

48.6 ms ± 2.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
722 μs ± 45.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


---
## 4️⃣ Broadcasting

NumPy puede operar arrays de distinta forma si son compatibles.

Ejemplo simple:

In [6]:
mat = np.array([[1,2,3],[4,5,6]])
mat + np.array([10,20,30])

array([[11, 22, 33],
       [14, 25, 36]])

---
## 5️⃣ Tipos (`dtype`)

NumPy permite controlar el tipo exacto:

In [17]:
np.array([1,2,3], dtype=np.float32), np.array([1,2,3], dtype=np.int8)

(array([1., 2., 3.], dtype=float32), array([1, 2, 3], dtype=int8))

In [13]:
## 6- SLICING
#############
a = np.array([1, 2, 3, 4, 5, 6])

print(a[1:4])
print(a[:3])
print(a[::2]) # obtener valores con salto dos (1 sí, 1 no)
print(a[a % 2 == 0]) # obtener valores pares


[2 3 4]
[1 2 3]
[1 3 5]
[2 4 6]


---
## 6️⃣ Ejercicio práctico

### 🧩 Ejercicio
Crea un array de números del 1 al 20.
- Consigue todos los valores pares usando slicing
- Multiplica esos pares por 3 (vectorizado)
- Cambia el tipo del array resultante a `float32`

Escribe tu solución abajo:

In [ ]:
import numpy as np

datos = np.arange(1,21)
print("Datos ini:", datos)

pares = datos[datos % 2 == 0]
print("Datos pares:", pares)

por_tres = 3 * pares
print("Datos por tres:", por_tres)

por_tres_fl = np.array(por_tres, dtype=np.float32)
print("Datos por tres:", por_tres_fl)

print("Datos ini:", datos)

Datos ini: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Datos pares: [ 2  4  6  8 10 12 14 16 18 20]
Datos por tres: [ 6 12 18 24 30 36 42 48 54 60]
Datos por tres: [ 6. 12. 18. 24. 30. 36. 42. 48. 54. 60.]


AttributeError: 'numpy.ndarray' object has no attribute 'atype'

---
## ✅ Solución (oculta)

<details>
<summary>Mostrar solución</summary>

```python
x = np.arange(1,21)
pares = x[x%2==0]
res = pares * 3
res.astype(np.float32)
```
</details>