# 🧮 Módulo 6 — NumPy: Álgebra Lineal

NumPy incluye el módulo `numpy.linalg`, con herramientas para:

- Producto punto
- Multiplicación de matrices
- Matrices transpuestas
- Determinantes
- Matrices inversas
- Autovalores y autovectores
- Resolución de sistemas lineales

Este notebook cubre los fundamentos para análisis estadístico, ML, física, economía y más.

---
## 1️⃣ Producto punto (`dot`)

Para vectores:

In [3]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print("Array A:", a)
print("Array B:", b)
print("Operacion dot (A x B):", np.dot(a, b))
print("Operacion Interseccion (@):", a @ b)

Array A: [1 2 3]
Array B: [4 5 6]
Operacion dot (A x B): 32
Operacion Interseccion (@): 32


---
## 2️⃣ Multiplicación matricial

Para matrices 2D, `@` es equivalente a `dot()`.

In [ ]:
# Tambien es equivalente con matrices de 2 dimensiones. A partir de 3, ya no
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Matriz 2D A:", A)
print("Matriz 2D B:", B)
print("Operacion dot (A x B):", np.dot(A, B))
print("Operacion Interseccion (@):", A @ B)

Matriz A: [1 2 3]
Matriz B: [4 5 6]
Operacion dot (A x B): [[19 22]
 [43 50]]
Operacion Interseccion (@): [[19 22]
 [43 50]]


In [ ]:
# Tambien es equivalente con matrices de 2 dimensiones. A partir de 3, ya no
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[5,6],[7,8]])

print("Matriz 3D C:", C)
print("Matriz 3D D:", D)
print("Operacion dot (A x B):", np.dot(A, B))
print("Operacion Interseccion (@):", A @ B)

---
## 3️⃣ Traspuesta

`.T` devuelve una vista transpuesta:

In [7]:
A.T

array([[1, 3],
       [2, 4]])

---
## 4️⃣ Determinante

Usando `numpy.linalg.det`:

In [8]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

---
## 5️⃣ Inversa de una matriz

`numpy.linalg.inv()` calcula la inversa si existe.

In [9]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

---
## 6️⃣ Autovalores y autovectores

Muy utilizados en PCA, análisis espectral, dinámica, optimización...

In [10]:
valores, vectores = np.linalg.eig(A)
valores, vectores

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

---
## 7️⃣ Resolver sistemas lineales

Resolver:
```
3x + y  = 9
x + 2y = 8
```

In [11]:
coef = np.array([[3,1],[1,2]])
cons = np.array([9,8])

np.linalg.solve(coef, cons)

array([2., 3.])

---
## 8️⃣ Ejemplo real: regresión lineal (mínimos cuadrados)

Resolver `Ax ≈ b` mediante pseudoinversa:

In [12]:
x = np.array([1,2,3,4])
y = np.array([2,4,5,4])

A = np.vstack([x, np.ones(len(x))]).T
coef, resid, *_ = np.linalg.lstsq(A, y, rcond=None)

coef  # pendiente y ordenada

array([0.7, 2. ])

---
## 9️⃣ Ejercicio práctico

Dada la matriz:
```python
M = np.array([[2,1],[5,7]])
```

### 🧩 Objetivos
1. Calcula el determinante
2. Calcula la inversa
3. Verifica que `M @ M_inv ≈ I`
4. Halla autovalores y autovectores

Escribe tu solución aquí:

In [ ]:
M = np.array([[2,1],[5,7]])

print("Datos ini:", M)

detM = np.linalg.det(M)
print("1. Determinante:", detM)

invM = np.linalg.inv(M)
print("2. Inversa:", invM)

prodM = M @ invM
print("3. Interseccion:", prodM)

autovalM, autovecM = np.linalg.eig(M)
print("4. Autovalores:", autovalM)
print("4. Autovectores:", autovecM)

print("3. Datos fin:", M)


Datos ini: [[2 1]
 [5 7]]
1. Determinante: 9.000000000000002
2. Inversa: [[ 0.77777778 -0.11111111]
 [-0.55555556  0.22222222]]
3. Interseccion: [[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]
4. Autovalores: [1.14589803 7.85410197]
4. Autovectores: [[-0.76039797 -0.16838141]
 [ 0.6494574  -0.98572192]]
3. Datos fin: [[2 1]
 [5 7]]


---
## ✅ Solución (oculta)

    
<details>
<summary>Mostrar solución</summary>

```python
M = np.array([[2,1],[5,7]])

det = np.linalg.det(M)
inv = np.linalg.inv(M)
ident = M @ inv
eigvals, eigvecs = np.linalg.eig(M)

det, inv, ident, eigvals, eigvecs
```
</details>