# 🧪 Laboratorio — NumPy Completo

Este laboratorio reúne todo lo aprendido en el módulo NumPy:

- Creación y propiedades de arrays
- Formas y `reshape`
- Indexación básica y avanzada
- Copias vs vistas
- Álgebra lineal
- Ejercicios integrados de análisis numérico

Completa cada sección antes de ver la solución.

---
## 1️⃣ Fundamentos — Crear arrays

### 🧩 Ejercicio
Crea un array `x` con los números del 1 al 20.
- Obtén sus dimensiones (`ndim`), forma (`shape`) y tipo (`dtype`).
- Convierte el array a `float32`.

Escribe tu solución aquí:

In [ ]:
import numpy as np

x = np.arange(1,21)
print("Datos ini:", x)
print("Dim:", x.ndim, " - Size:", x.size, " - Shape:", x.shape, " - Type:", x.dtype)

x_fl = np.array(x, dtype=np.float32)
print("Datos float:", x_fl)



Datos ini: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Dim: 1  - Size: 20  - Shape: (20,)  - Type: int64
Datos pfloat: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]


---
## 2️⃣ Formas y `reshape`

### 🧩 Ejercicio
Con el array `x`:
1. Convierte `x` en una matriz 4×5
2. Aplánala usando `ravel()`
3. Aplánala usando `flatten()`

Compara si las dos versiones comparten memoria.

In [ ]:
import numpy as np

m = x.reshape(4,5)
print("Matriz ini:", m)

m_r = x.ravel()
print("Ravel:", m_r)

m_f = x.flatten()
print("Flatten:", m_f)

print("Mem compartida matriz-ravel:", np.shares_memory(m, m_r))
print("Mem compartida matriz-flatten:", np.shares_memory(m, m_f))


Matriz ini: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Mem compartida matriz-ravel: True
Mem compartida matriz-flatten: False


---
## 3️⃣ Indexación básica, slicing y booleana

### 🧩 Ejercicio
Dada la matriz:
```python
m = np.arange(1,17).reshape(4,4)
```
Haz lo siguiente:
1. Extrae la segunda fila
2. Extrae la segunda columna
3. Extrae el bloque central 2×2
4. Obtén los números mayores a 10 usando indexación booleana
5. Usa fancy indexing para obtener la diagonal inversa

Escribe aquí tu código:

In [ ]:
import numpy as np

m = np.arange(1,17).reshape(4,4)

print("Datos ini:", m)

fila_vista = m[1]
print("1. 2º Fila (vista):", fila_vista)

#col_vista = m.T[1]
col_vista = m[:,1]
print("1. 2º Columna (vista):", col_vista)

#centro = m[[2,3],[2,3]] MAL!!
#centro = m[:2, :2] MAL!!!
centro = m[1:3, 1:3]
print("3. Centro 2x2:", centro)

filtro10 = m[m > 10]
print("4. Mayor que 10:", filtro10)

mdi = m[[0,1,2,3], [3,2,1,0]]
print("5. Diagonal inversa:", mdi)

print("Datos fin:", m)



Datos ini: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
1. 2º Fila (vista): [5 6 7 8]
1. 2º Columna (vista): [ 2  6 10 14]
3. Centro 2x2: [[ 6  7]
 [10 11]]
4. Mayor que 10: [11 12 13 14 15 16]
5. Diagonal inversa: [ 4  7 10 13]
Datos fin: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


---
## 4️⃣ Copias vs Vistas — Comportamiento real

### 🧩 Ejercicio
Usa el mismo array `m`:

1. Obtén una vista de la primera fila y modifica un valor
2. Comprueba si `m` cambia
3. Obtén una copia de esa fila y modifica un valor
4. Comprueba si `m` cambia
5. Usa `np.shares_memory` para documentar el resultado

Escribe tu solución aquí:

In [ ]:
import numpy as np

m2 = np.arange(1,17).reshape(4,4)

print("//--- Datos ini:, "---//"", m2)

fila_vista = m2[0]
print("1. 1º Fila (vista):", fila_vista)

fila_vista[1] = 999
print("2. 1º Fila (vista) con cambio:", fila_vista)
print("2. Datos:", m2)


fila_copia = m2[0].copy()
print("3. 1º Fila (copia):", fila_copia)

fila_copia[0] = 999
print("4. 1º Fila (copia) con cambio:", fila_copia)
print("5. Datos:", m2)

print("5. Mem compartida matriz-vista:", np.shares_memory(m2, fila_vista))
print("5. Mem compartida matriz-copia:", np.shares_memory(m2, fila_copia))

print("//--- Datos fin:", m2, "---//")



Datos ini: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
1. 1º Fila (vista): [1 2 3 4]
2. 1º Fila (vista) con cambio: [  1 999   3   4]
2. Datos: [[  1 999   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14  15  16]]
3. 1º Fila (copia): [  1 999   3   4]
4. 1º Fila (copia) con cambio: [999 999   3   4]
5. Datos: [[  1 999   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14  15  16]]
5. Mem compartida matriz-vista: True
5. Mem compartida matriz-copia: False
Datos fin: [[  1 999   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14  15  16]]


---
## 5️⃣ Álgebra lineal — ejercicios aplicados

### 🧩 Problema A — Matriz cuadrada
Dada:
```python
A = np.array([[3,1],[2,4]])
```
Calcula:
1. Determinante
2. Inversa
3. Autovalores y autovectores
4. Verifica que `A @ inv ≈ I`

### 🧩 Problema B — Sistema lineal
Resuelve:
```
2x + y = 10
x + 3y = 13
```
Escribe aquí tu solución:

In [3]:
import numpy as np

A = np.array([[3,1],[2,4]])

print("//--- Datos ini:", A, "---//")

detA = np.linalg.det(A)
print("1. Determinante:", detA)

invA = np.linalg.inv(A)
print("2. Inversa:", invA)

autovalA, autovecA = np.linalg.eig(A)
print("3. Autovalores:", autovalA)
print("3. Autovectores:", autovecA)

prodA = A @ invA
print("4. Interseccion:", prodA)

print("//--- Datos fin:", A, "---//")


//--- Datos ini: [[3 1]
 [2 4]] ---//
1. Determinante: 10.000000000000002
2. Inversa: [[ 0.4 -0.1]
 [-0.2  0.3]]
3. Autovalores: [2. 5.]
3. Autovectores: [[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]
4. Interseccion: [[1. 0.]
 [0. 1.]]
//--- Datos fin: [[3 1]
 [2 4]] ---//


---
## 6️⃣ Ejercicio integrador — Dataset numérico

Dado un dataset simulado (puntuaciones por examen):
```python
notas = np.array([
    [7,8,9],
    [5,6,7],
    [9,9,10],
    [4,5,6]
])
```
### 🧩 Objetivo
1. Calcula la media por alumno
2. Calcula la media por examen
3. Obtén una matriz normalizada restando la media por examen
4. Calcula el vector de varianzas por examen
5. Extrae los valores mayores a 8 usando boolean indexing

Escribe aquí tu trabajo:

In [ ]:
import numpy as np

notas = np.array([
    [7,8,9],
    [5,6,7],
    [9,9,10],
    [4,5,6]
])

print("//--- Datos ini:", notas, "---//")

#media =
#print("1. Media por alumno:", media)

notasEx = notas.T
print("Matriz de notas por examen:", notasEx)

#mediaEx =
#print("1. Media por Examen:", mediaEx)

#notasNorma = notasEx - mediaEx
#print("3. Matriz normalizada:", notasNorma)

#print("4. Vector varianzas:", vecVar)

print("5. Mayores que 8:", notas[notas > 8])
print("//--- Datos fin:", notas, "---//")


//--- Datos ini: [[ 7  8  9]
 [ 5  6  7]
 [ 9  9 10]
 [ 4  5  6]] ---//
Matriz de notas por examen: [[ 7  5  9  4]
 [ 8  6  9  5]
 [ 9  7 10  6]]
5. Mayores que 8: [ 9  9  9 10]
//--- Datos fin: [[ 7  8  9]
 [ 5  6  7]
 [ 9  9 10]
 [ 4  5  6]] ---//


---
## ✅ Solución completa (oculta)

<details>
<summary>Mostrar soluciones</summary>

### ✔️ Fundamentos
```python
x = np.arange(1,21)
x.ndim, x.shape, x.dtype
x = x.astype(np.float32)
```

### ✔️ Reshape
```python
m = x.reshape(4,5)
r1 = m.ravel()
r2 = m.flatten()
np.shares_memory(m, r1), np.shares_memory(m, r2)
```

### ✔️ Indexación
```python
fila2 = m[1]
col2 = m[:,1]
bloque = m[1:3,1:3]
mayores10 = m[m>10]
diag_inv = m[[0,1,2,3],[3,2,1,0]]
```

### ✔️ Copias vs vistas
```python
v = m[0]
v[0] = 999

c = m[0].copy()
c[1] = 555

np.shares_memory(m, v), np.shares_memory(m, c)
```

### ✔️ Álgebra lineal
```python
A = np.array([[3,1],[2,4]])
det = np.linalg.det(A)
inv = np.linalg.inv(A)
eigvals, eigvecs = np.linalg.eig(A)
ident = A @ inv

coef = np.array([[2,1],[1,3]])
cons = np.array([10,13])
sol = np.linalg.solve(coef, cons)
```

### ✔️ Dataset
```python
media_alumno = notas.mean(axis=1)
media_examen = notas.mean(axis=0)
normalizada = notas - media_examen
varianzas = notas.var(axis=0)
mayores8 = notas[notas>8]
```
</details>